In [37]:
# importing the required libraries
import numpy as np
import pandas as pd

In [38]:
# loading the data into the pandas data frame
data = pd.read_csv("covid_19_data.csv")
data.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

### Initial data anaylsis

In [39]:
data.shape

(321, 6)

In [40]:
data.describe()

           Confirmed        Deaths      Recovered
count     321.000000    321.000000     321.000000
mean     9949.800623    709.152648    3030.277259
std     31923.853086   3236.162817   14364.870365
min         0.000000      0.000000       0.000000
25%       104.000000      2.000000       2.000000
50%       653.000000     12.000000      73.000000
75%      4655.000000    144.000000     587.000000
max    299691.000000  27682.000000  132929.000000

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321 entries, 0 to 320
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       321 non-null    object
 1   State      140 non-null    object
 2   Region     321 non-null    object
 3   Confirmed  321 non-null    int64
 4   Deaths     321 non-null    int64
 5   Recovered  321 non-null    int64
dtypes: int64(3), object(3)
memory usage: 15.2+ KB

In [42]:
data.isnull().sum()

Date           0
State        181
Region         0
Confirmed      0
Deaths         0
Recovered      0
dtype: int64

### Show the number of confirmed, deaths and recovered cases in each region.

In [43]:
data.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [44]:
data.groupby(by = "Region").sum()

                                  Confirmed  Deaths  Recovered
Region
Afghanistan                            1939      60        252
Albania                                 766      30        455
Algeria                                3848     444       1702
Andorra                                 743      42        423
Angola                                   27       2          7
Antigua and Barbuda                      24       3         11
Argentina                              4285     214       1192
Armenia                                1932      30        900
Australia                              6752      91       5715
Austria                               15402     580      12779
Azerbaijan                             1766      23       1267
Bahamas                                  80      11         23
Bahrain                                2921       8       1455
Bangladesh                             7103     163        150
Barbados                                 80       7         39
Belarus                               13181      84       2072
Belgium                               47859    7501      11283
Belize                                   18       2          9
Benin                                    64       1         33
Bhutan                                    7       0          5
Bolivia                                1110      59        117
Bosnia and Herzegovina                 1677      65        710
Botswana                                 23       1          5
Brazil                                79685    5513      34132
Brunei                                  138       1        124
Bulgaria                               1447      64        243
Burkina Faso                            641      43        498
Burma                                   150       6         27
Burundi                                  11       1          4
Cabo Verde                              114       1          2
Cambodia                                122       0        119
Cameroon                               1832      61        934
Canada                                52865    3155      20327
Central African Republic                 50       0         10
Chad                                     52       2         19
Chile                                 14885     216       8057
Colombia                               6207     278       1411
Congo (Brazzaville)                     207       8         19
Congo (Kinshasa)                        491      30         59
Costa Rica                              713       6        323
Croatia                                2062      67       1288
Cuba                                   1467      58        617
Cyprus                                  843      15        148
Czech Republic                         7579     227       3108
Denmark                                9206     443       6558
Diamond Princess                        712      13        645
Djibouti                               1077       2        599
Dominica                                 16       0         13
Dominican Republic                     6652     293       1228
Ecuador                               24675     883       1557
Egypt                                  5268     380       1335
El Salvador                             377       9        106
Equatorial Guinea                       315       1          9
Eritrea                                  39       0         19
Estonia                                1666      50        236
Eswatini                                 91       1         10
Ethiopia                                130       3         58
Fiji                                     18       0         12
Finland                                4906     206       2800
France                               166543   24121      49118
Gabon                                   276       3         67
Gambia                                   10       1          8
Georgia                                 517       6        178
Germany                              161539    6467     120400
Ghana                                  1671      16        188
Greece                                 2576     139        577
Grenada                                  20       0         13
Guatemala                               557      16         62
Guinea                                 1351       7        313
Guinea-Bissau                           205       1         19
Guyana                                   78       8         18
Haiti                                    76       6          8
Holy See                                 10       0          2
Honduras                                738      66         73
Hong Kong                              1037       4        830
Hungary                                2727     300        536
Iceland                                1797      10       1656
India                                 33062    1079       8437
Indonesia                              9771     784       1391
Iran                                  93657    5957      73791
Iraq                                   2003      92       1346
Ireland                               20253    1190      13386
Israel                                15834     215       8233
Italy                                203591   27682      71252
Ivory Coast                            1238      14        557
Jamaica                                 396       7         29
Japan                                 13895     413       2368
Jordan                                  451       8        356
Kazakhstan                             3138      25        819
Kenya                                   384      15        129
Kosovo                                  510      12         93
Kuwait                                 3740      24       1389
Kyrgyzstan                              729       8        437
Laos                                     19       0          7
Latvia                                  849      15        348
Lebanon                                 721      24        150
Liberia                                 141      16         45
Libya                                    61       2         18
Liechtenstein                            82       1         55
Lithuania                              1375      45        563
Luxembourg                             3769      89       3134
MS Zaandam                                9       2          0
Macau                                    45       0         34
Madagascar                              128       0         90
Mainland China                        82862    4633      77610
Malawi                                   36       3          7
Malaysia                               5945     100       4087
Maldives                                278       1         17
Mali                                    482      25        129
Malta                                   463       4        339
Mauritania                                8       1          6
Mauritius                               332      10        306
Mexico                                17799    1732      11423
Moldova                                3771     111       1114
Monaco                                   95       4         58
Mongolia                                 38       0         10
Montenegro                              322       7        203
Morocco                                4321     168        928
Mozambique                               76       0         12
Namibia                                  16       0          8
Nepal                                    57       0         16
Netherlands                           38998    4727        119
New Zealand                            1476      19       1241
Nicaragua                                13       3          7
Niger                                   713      32        435
Nigeria                                1728      51        307
North Macedonia                        1442      73        627
Norway                                 7710     207         32
Oman                                   2274      10        364
Pakistan                              15525     343       3425
Panama                                 6378     178        527
Papua New Guinea                          8       0          0
Paraguay                                239       9        102
Peru                                  33931     943      10037
Philippines                            8212     558       1023
Poland                                12640     624       3025
Portugal                              24505     973       1470
Qatar                                 12564      10       1243
Romania                               11978     693       3569
Russia                                99399     972      10286
Rwanda                                  225       0         98
Saint Kitts and Nevis                    15       0          4
Saint Lucia                              17       0         15
Saint Vincent and the Grenadines         16       0          8
San Marino                              563      41         69
Sao Tome and Principe                     8       0          4
Saudi Arabia                          21402     157       2953
Senegal                                 882       9        315
Serbia                                 6630     125        870
Seychelles                               11       0          6
Sierra Leone                            104       4         12
Singapore                             15641      14       1188
Slovakia                               1391      22        484
Slovenia                               1418      89        230
Somalia                                 582      28         20
South Africa                           5350     103       2073
South Korea                           10765     247       9059
South Sudan                              34       0          0
Spain                                236899   24275     132929
Sri Lanka                               649       7        136
Sudan                                   375      28         32
Suriname                                 10       1          8
Sweden                                20302    2462       1005
Switzerland                           29407    1716      22600
Syria                                    43       3         21
Taiwan                                  429       6        311
Tanzania                                480      16        167
Thailand                               2947      54       2665
Timor-Leste                              24       0          6
Togo                                    109       7         64
Trinidad and Tobago                     116       8         71
Tunisia                                 980      40        294
Turkey                               117589    3081      44040
UK                                   166441   26166        857
US                                  1039909   60967     120720
Uganda                                   81       0         52
Ukraine                                9866     250       1103
United Arab Emirates                  11929      98       2329
Uruguay                                 630      15        412
Uzbekistan                             2002       9       1096
Venezuela                               331      10        142
Vietnam                                 270       0        222
West Bank and Gaza                      344       2         71
Western Sahara                            6       0          5
Yemen                                     6       0          1
Zambia                                   97       3         54
Zimbabwe                                 32       4          5

### Remove all the records where confimed cases is less than 10.

In [45]:
data.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [46]:
data = data[~(data["Confirmed"]<10)]

In [47]:
data.shape

(304, 6)

### In which region maximum number of confirmed cases were recorded?

In [48]:
data.groupby(by = "Region")["Confirmed"].sum().sort_values(ascending = False)

# Answer - US

Region
US                                  1039909
Spain                                236899
Italy                                203591
France                               166536
UK                                   166432
Germany                              161539
Turkey                               117589
Russia                                99399
Iran                                  93657
Mainland China                        82861
Brazil                                79685
Canada                                52860
Belgium                               47859
Netherlands                           38993
Peru                                  33931
India                                 33062
Switzerland                           29407
Ecuador                               24675
Portugal                              24505
Saudi Arabia                          21402
Sweden                                20302
Ireland                               20253
Mexico                                17799
Israel                                15834
Singapore                             15641
Pakistan                              15525
Austria                               15402
Chile                                 14885
Japan                                 13895
Belarus                               13181
Poland                                12640
Qatar                                 12564
Romania                               11978
United Arab Emirates                  11929
South Korea                           10765
Ukraine                                9866
Indonesia                              9771
Denmark                                9206
Philippines                            8212
Norway                                 7710
Czech Republic                         7579
Bangladesh                             7103
Australia                              6752
Dominican Republic                     6652
Serbia                                 6630
Panama                                 6378
Colombia                               6207
Malaysia                               5945
South Africa                           5350
Egypt                                  5268
Finland                                4906
Morocco                                4321
Argentina                              4285
Algeria                                3848
Moldova                                3771
Luxembourg                             3769
Kuwait                                 3740
Kazakhstan                             3138
Thailand                               2947
Bahrain                                2921
Hungary                                2727
Greece                                 2576
Oman                                   2274
Croatia                                2062
Iraq                                   2003
Uzbekistan                             2002
Afghanistan                            1939
Armenia                                1932
Cameroon                               1832
Iceland                                1797
Azerbaijan                             1766
Nigeria                                1728
Bosnia and Herzegovina                 1677
Ghana                                  1671
Estonia                                1666
New Zealand                            1476
Cuba                                   1467
Bulgaria                               1447
North Macedonia                        1442
Slovenia                               1418
Slovakia                               1391
Lithuania                              1375
Guinea                                 1351
Ivory Coast                            1238
Bolivia                                1110
Djibouti                               1077
Hong Kong                              1037
Tunisia                                 980
Senegal                                 882
Latvia                                  849
Cyprus                                  843
Albania                                 766
Andorra                                 743
Honduras                                738
Kyrgyzstan                              729
Lebanon                                 721
Niger                                   713
Costa Rica                              713
Diamond Princess                        712
Sri Lanka                               649
Burkina Faso                            641
Uruguay                                 630
Somalia                                 582
San Marino                              563
Guatemala                               557
Georgia                                 517
Kosovo                                  510
Congo (Kinshasa)                        491
Mali                                    482
Tanzania                                480
Malta                                   463
Jordan                                  451
Taiwan                                  429
Jamaica                                 396
Kenya                                   384
El Salvador                             377
Sudan                                   375
West Bank and Gaza                      344
Mauritius                               332
Venezuela                               331
Montenegro                              322
Equatorial Guinea                       315
Maldives                                278
Gabon                                   276
Vietnam                                 270
Paraguay                                239
Rwanda                                  225
Congo (Brazzaville)                     207
Guinea-Bissau                           205
Burma                                   150
Liberia                                 141
Brunei                                  138
Ethiopia                                130
Madagascar                              128
Cambodia                                122
Trinidad and Tobago                     116
Cabo Verde                              114
Togo                                    109
Sierra Leone                            104
Zambia                                   97
Monaco                                   95
Eswatini                                 91
Liechtenstein                            82
Uganda                                   81
Bahamas                                  80
Barbados                                 80
Guyana                                   78
Haiti                                    76
Mozambique                               76
Benin                                    64
Libya                                    61
Nepal                                    57
Chad                                     52
Central African Republic                 50
Macau                                    45
Syria                                    43
Eritrea                                  39
Mongolia                                 38
Malawi                                   36
South Sudan                              34
Zimbabwe                                 32
Angola                                   27
Timor-Leste                              24
Antigua and Barbuda                      24
Botswana                                 23
Grenada                                  20
Laos                                     19
Belize                                   18
Fiji                                     18
Saint Lucia                              17
Saint Vincent and the Grenadines         16
Namibia                                  16
Dominica                                 16
Saint Kitts and Nevis                    15
Nicaragua                                13
Seychelles                               11
Burundi                                  11
Holy See                                 10
Gambia                                   10
Suriname                                 10
Name: Confirmed, dtype: int64

### In which region minimum number of deaths were recorded ?

In [49]:
data.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [50]:
data.groupby(by = "Region")["Deaths"].sum().sort_values().head(30)

Region
Cambodia                            0
Seychelles                          0
Saint Lucia                         0
Central African Republic            0
Saint Kitts and Nevis               0
South Sudan                         0
Rwanda                              0
Grenada                             0
Macau                               0
Madagascar                          0
Nepal                               0
Namibia                             0
Saint Vincent and the Grenadines    0
Mozambique                          0
Holy See                            0
Timor-Leste                         0
Mongolia                            0
Uganda                              0
Laos                                0
Eritrea                             0
Vietnam                             0
Fiji                                0
Dominica                            0
Gambia                              1
Equatorial Guinea                   1
Eswatini                            1
Cabo Verde                          1
Maldives                            1
Guinea-Bissau                       1
Liechtenstein                       1
Name: Deaths, dtype: int64

### How many confirmed,deaths and recovered cases were reported from India till 29 April 2020 ?

In [51]:
data.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [52]:
data[data["Region"] == "India"]

         Date State Region  Confirmed  Deaths  Recovered
74  4/29/2020   NaN  India      33062    1079       8437

### Sort the entire data wrt to no of confirmed cases in ascending order.

In [53]:
data.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [54]:
data.sort_values(by = "Confirmed" , ascending=True)

,Date,State,Region,Confirmed,Deaths,Recovered
156,4/29/2020,NaN,Suriname,10,1,8
70,4/29/2020,NaN,Holy See,10,0,2
59,4/29/2020,NaN,Gambia,10,1,8
318,4/29/2020,Yukon,Canada,11,0,0
217,4/29/2020,Greenland,Denmark,11,0,11
256,4/29/2020,Montserrat,UK,11,1,2
144,4/29/2020,NaN,Seychelles,11,0,6
27,4/29/2020,NaN,Burundi,11,1,4
306,4/29/2020,Turks and Caicos Islands,UK,12,1,5
118,4/29/2020,NaN,Nicaragua,13,3,7
215,4/29/2020,Grand Princess,Canada,13,0,0
206,4/29/2020,Falkland Islands (Malvinas),UK,13,0,11
270,4/29/2020,Northern Mariana Islands,US,14,2,0
136,4/29/2020,NaN,Saint Kitts and Nevis,15,0,4
138,4/29/2020,NaN,Saint Vincent and the Grenadines,16,0,8
45,4/29/2020,NaN,Dominica,16,0,13
201,4/29/2020,Curacao,Netherlands,16,1,13
114,4/29/2020,NaN,Namibia,16,0,8
137,4/29/2020,NaN,Saint Lucia,17,0,15
260,4/29/2020,New Caledonia,France,18,0,17
16,4/29/2020,NaN,Belize,18,2,9
55,4/29/2020,NaN,Fiji,18,0,12
281,4/29/2020,Qinghai,Mainland China,18,0,18
90,4/29/2020,NaN,Laos,19,0,7
64,4/29/2020,NaN,Grenada,20,0,13
21,4/29/2020,NaN,Botswana,23,1,5
5,4/29/2020,NaN,Antigua and Barbuda,24,3,11
163,4/29/2020,NaN,Timor-Leste,24,0,6
279,4/29/2020,Prince Edward Island,Canada,27,0,0
4,4/29/2020,NaN,Angola,27,2,7
271,4/29/2020,Northern Territory,Australia,28,0,25
180,4/29/2020,NaN,Zimbabwe,32,4,5
152,4/29/2020,NaN,South Sudan,34,0,0
100,4/29/2020,NaN,Malawi,36,3,7
300,4/29/2020,St Martin,France,38,3,24
110,4/29/2020,NaN,Mongolia,38,0,10
51,4/29/2020,NaN,Eritrea,39,0,19
159,4/29/2020,NaN,Syria,43,3,21
244,4/29/2020,Macau,Macau,45,0,34
204,4/29/2020,Diamond Princess cruise ship,US,49,0,0
31,4/29/2020,NaN,Central African Republic,50,0,10
32,4/29/2020,NaN,Chad,52,2,19
310,4/29/2020,Virgin Islands,US,57,4,0
115,4/29/2020,NaN,Nepal,57,0,16
210,4/29/2020,French Polynesia,France,58,0,50
94,4/29/2020,NaN,Libya,61,2,18
17,4/29/2020,NaN,Benin,64,1,33
196,4/29/2020,Cayman Islands,UK,73,1,10
296,4/29/2020,Sint Maarten,Netherlands,75,13,33
267,4/29/2020,Ningxia,Mainland China,75,0,75
317,4/29/2020,Xinjiang,Mainland China,76,3,73
113,4/29/2020,NaN,Mozambique,76,0,12
69,4/29/2020,NaN,Haiti,76,6,8
68,4/29/2020,NaN,Guyana,78,8,18
13,4/29/2020,NaN,Barbados,80,7,39
10,4/29/2020,NaN,Bahamas,80,11,23
169,4/29/2020,NaN,Uganda,81,0,52
95,4/29/2020,NaN,Liechtenstein,82,1,55
53,4/29/2020,NaN,Eswatini,91,1,10
109,4/29/2020,NaN,Monaco,95,4,58
179,4/29/2020,NaN,Zambia,97,3,54
188,4/29/2020,Aruba,Netherlands,100,2,73
216,4/29/2020,Grand Princess,US,103,3,0
145,4/29/2020,NaN,Sierra Leone,104,4,12
189,4/29/2020,Australian Capital Territory,Australia,106,3,101
164,4/29/2020,NaN,Togo,109,7,64
239,4/29/2020,Jilin,Mainland China,111,1,99
191,4/29/2020,Bermuda,UK,111,6,48
28,4/29/2020,NaN,Cabo Verde,114,1,2
165,4/29/2020,NaN,Trinidad and Tobago,116,8,71
259,4/29/2020,New Brunswick,Canada,118,0,0
29,4/29/2020,NaN,Cambodia,122,0,119
209,4/29/2020,French Guiana,France,125,1,93
99,4/29/2020,NaN,Madagascar,128,0,90
54,4/29/2020,NaN,Ethiopia,130,3,58
23,4/29/2020,NaN,Brunei,138,1,124
212,4/29/2020,Gansu,Mainland China,139,2,137
214,4/29/2020,Gibraltar,UK,141,0,131
219,4/29/2020,Guam,US,141,5,0
93,4/29/2020,NaN,Liberia,141,16,45
242,4/29/2020,Liaoning,Mainland China,146,2,143
222,4/29/2020,Guizhou,Mainland China,147,2,145
218,4/29/2020,Guadeloupe,France,149,12,82
26,4/29/2020,NaN,Burma,150,6,27
223,4/29/2020,Hainan,Mainland China,168,6,162
247,4/29/2020,Martinique,France,175,14,83
319,4/29/2020,Yunnan,Mainland China,185,2,181
207,4/29/2020,Faroe Islands,Denmark,187,0,181
304,4/29/2020,Tianjin,Mainland China,190,3,183
294,4/29/2020,Shanxi,Mainland China,197,0,164
234,4/29/2020,Inner Mongolia,Mainland China,200,1,150
67,4/29/2020,NaN,Guinea-Bissau,205,1,19
35,4/29/2020,NaN,Congo (Brazzaville),207,8,19
301,4/29/2020,Tasmania,Australia,219,12,144
135,4/29/2020,NaN,Rwanda,225,0,98
127,4/29/2020,NaN,Paraguay,239,9,102
221,4/29/2020,Guangxi,Mainland China,254,2,252
266,4/29/2020,Newfoundland and Labrador,Canada,258,3,0
175,4/29/2020,NaN,Vietnam,270,0,222
246,4/29/2020,Manitoba,Canada,275,6,0
58,4/29/2020,NaN,Gabon,276,3,67
102,4/29/2020,NaN,Maldives,278,1,17
291,4/29/2020,Shaanxi,Mainland China,306,3,253
236,4/29/2020,Isle of Man,UK,313,21,258
50,4/29/2020,NaN,Equatorial Guinea,315,1,9
111,4/29/2020,NaN,Montenegro,322,7,203
225,4/29/2020,Hebei,Mainland China,328,6,318
174,4/29/2020,NaN,Venezuela,331,10,142
106,4/29/2020,NaN,Mauritius,332,10,306
176,4/29/2020,NaN,West Bank and Gaza,344,2,71
182,4/29/2020,Alaska,US,355,9,0
211,4/29/2020,Fujian,Mainland China,355,1,353
155,4/29/2020,NaN,Sudan,375,28,32
49,4/29/2020,NaN,El Salvador,377,9,106
290,4/29/2020,Saskatchewan,Canada,383,6,0
86,4/29/2020,NaN,Kenya,384,15,129
82,4/29/2020,NaN,Jamaica,396,7,29
286,4/29/2020,Reunion,France,420,0,300
160,4/29/2020,NaN,Taiwan,429,6,311
297,4/29/2020,South Australia,Australia,438,4,420
84,4/29/2020,NaN,Jordan,451,8,356
255,4/29/2020,Montana,US,451,16,0
250,4/29/2020,Mayotte,France,460,4,235
104,4/29/2020,NaN,Malta,463,4,339
161,4/29/2020,NaN,Tanzania,480,16,167
103,4/29/2020,NaN,Mali,482,25,129
36,4/29/2020,NaN,Congo (Kinshasa),491,30,59
87,4/29/2020,NaN,Kosovo,510,12,93
60,4/29/2020,NaN,Georgia,517,6,178
197,4/29/2020,Channel Islands,UK,537,38,386
316,4/29/2020,Wyoming,US,545,7,0
314,4/29/2020,Western Australia,Australia,551,8,507
65,4/29/2020,NaN,Guatemala,557,16,62
295,4/29/2020,Sichuan,Mainland China,561,3,558
139,4/29/2020,NaN,San Marino,563,41,69
198,4/29/2020,Chongqing,Mainland China,579,6,573
149,4/29/2020,NaN,Somalia,582,28,20
190,4/29/2020,Beijing,Mainland China,593,9,542
224,4/29/2020,Hawaii,US,613,16,0
172,4/29/2020,NaN,Uruguay,630,15,412
25,4/29/2020,NaN,Burkina Faso,641,43,498
293,4/29/2020,Shanghai,Mainland China,647,7,597
154,4/29/2020,NaN,Sri Lanka,649,7,136
237,4/29/2020,Jiangsu,Mainland China,653,0,648
43,4/29/2020,NaN,Diamond Princess,712,13,645
119,4/29/2020,NaN,Niger,713,32,435
37,4/29/2020,NaN,Costa Rica,713,6,323
92,4/29/2020,NaN,Lebanon,721,24,150
89,4/29/2020,NaN,Kyrgyzstan,729,8,437
71,4/29/2020,NaN,Honduras,738,66,73
3,4/29/2020,NaN,Andorra,743,42,423
1,4/29/2020,NaN,Albania,766,30,455
292,4/29/2020,Shandong,Mainland China,787,7,772
40,4/29/2020,NaN,Cyprus,843,15,148
91,4/29/2020,NaN,Latvia,849,15,348
308,4/29/2020,Vermont,US,862,47,0
142,4/29/2020,NaN,Senegal,882,9,315
273,4/29/2020,Nova Scotia,Canada,935,28,0
238,4/29/2020,Jiangxi,Mainland China,937,1,936
226,4/29/2020,Heilongjiang,Mainland China,939,13,587
166,4/29/2020,NaN,Tunisia,980,40,294
185,4/29/2020,Anhui,Mainland China,991,6,985
230,4/29/2020,Hunan,Mainland China,1019,4,1015
283,4/29/2020,Queensland,Australia,1033,6,943
269,4/29/2020,North Dakota,US,1033,19,0
228,4/29/2020,Hong Kong,Hong Kong,1037,4,830
245,4/29/2020,Maine,US,1056,52,0
44,4/29/2020,NaN,Djibouti,1077,2,599
313,4/29/2020,West Virginia,US,1110,38,0
19,4/29/2020,NaN,Bolivia,1110,59,117
81,4/29/2020,NaN,Ivory Coast,1238,14,557
320,4/29/2020,Zhejiang,Mainland China,1268,1,1263
227,4/29/2020,Henan,Mainland China,1276,22,1254
66,4/29/2020,NaN,Guinea,1351,7,313
309,4/29/2020,Victoria,Australia,1361,18,1291
96,4/29/2020,NaN,Lithuania,1375,45,563
147,4/29/2020,NaN,Slovakia,1391,22,484
148,4/29/2020,NaN,Slovenia,1418,89,230
280,4/29/2020,Puerto Rico,US,1433,86,0
121,4/29/2020,NaN,North Macedonia,1442,73,627
24,4/29/2020,NaN,Bulgaria,1447,64,243
39,4/29/2020,NaN,Cuba,1467,58,617
117,4/29/2020,NaN,New Zealand,1476,19,1241
220,4/29/2020,Guangdong,Mainland China,1588,8,1557
52,4/29/2020,NaN,Estonia,1666,50,236
62,4/29/2020,NaN,Ghana,1671,16,188
20,4/29/2020,NaN,Bosnia and Herzegovina,1677,65,710
120,4/29/2020,NaN,Nigeria,1728,51,307
9,4/29/2020,NaN,Azerbaijan,1766,23,1267
73,4/29/2020,NaN,Iceland,1797,10,1656
30,4/29/2020,NaN,Cameroon,1832,61,934
7,4/29/2020,NaN,Armenia,1932,30,900
0,4/29/2020,NaN,Afghanistan,1939,60,252
231,4/29/2020,Idaho,US,1952,60,0
173,4/29/2020,NaN,Uzbekistan,2002,9,1096
77,4/29/2020,NaN,Iraq,2003,92,1346
261,4/29/2020,New Hampshire,US,2058,60,0
38,4/29/2020,NaN,Croatia,2062,67,1288
193,4/29/2020,British Columbia,Canada,2087,109,0
123,4/29/2020,NaN,Oman,2274,10,364
299,4/29/2020,South Dakota,US,2373,13,0
277,4/29/2020,Oregon,US,2446,101,0
63,4/29/2020,NaN,Greece,2576,139,577
72,4/29/2020,NaN,Hungary,2727,300,536
11,4/29/2020,NaN,Bahrain,2921,8,1455
162,4/29/2020,NaN,Thailand,2947,54,2665
264,4/29/2020,New South Wales,Australia,3016,40,2284
85,4/29/2020,NaN,Kazakhstan,3138,25,819
187,4/29/2020,Arkansas,US,3193,57,0
263,4/29/2020,New Mexico,US,3213,112,0
275,4/29/2020,Oklahoma,US,3473,214,0
88,4/29/2020,NaN,Kuwait,3740,24,1389
97,4/29/2020,NaN,Luxembourg,3769,89,3134
108,4/29/2020,NaN,Moldova,3771,111,1114
240,4/29/2020,Kansas,US,3839,134,0
2,4/29/2020,NaN,Algeria,3848,444,1702
257,4/29/2020,Nebraska,US,3851,56,0
205,4/29/2020,District of Columbia,US,4106,205,0
6,4/29/2020,NaN,Argentina,4285,214,1192
112,4/29/2020,NaN,Morocco,4321,168,928
307,4/29/2020,Utah,US,4497,45,0
241,4/29/2020,Kentucky,US,4537,234,0
252,4/29/2020,Minnesota,US,4644,319,0
202,4/29/2020,Delaware,US,4655,144,0
56,4/29/2020,NaN,Finland,4906,206,2800
258,4/29/2020,Nevada,US,4934,230,0
183,4/29/2020,Alberta,Canada,5165,87,0
48,4/29/2020,NaN,Egypt,5268,380,1335
150,4/29/2020,NaN,South Africa,5350,103,2073
298,4/29/2020,South Carolina,US,5882,231,0
101,4/29/2020,NaN,Malaysia,5945,100,4087
34,4/29/2020,NaN,Colombia,6207,278,1411
125,4/29/2020,NaN,Panama,6378,178,527
315,4/29/2020,Wisconsin,US,6520,308,0
253,4/29/2020,Mississippi,US,6569,250,0
143,4/29/2020,NaN,Serbia,6630,125,870
46,4/29/2020,NaN,Dominican Republic,6652,293,1228
235,4/29/2020,Iowa,US,6843,148,0
181,4/29/2020,Alabama,US,6912,256,0
12,4/29/2020,NaN,Bangladesh,7103,163,150
186,4/29/2020,Arizona,US,7209,308,0
41,4/29/2020,NaN,Czech Republic,7579,227,3108
254,4/29/2020,Missouri,US,7660,338,0
122,4/29/2020,NaN,Norway,7710,207,32
129,4/29/2020,NaN,Philippines,8212,558,1023
287,4/29/2020,Rhode Island,US,8247,251,0
42,4/29/2020,NaN,Denmark,9008,443,6366
75,4/29/2020,NaN,Indonesia,9771,784,1391
170,4/29/2020,NaN,Ukraine,9866,250,1103
268,4/29/2020,North Carolina,US,10180,382,0
302,4/29/2020,Tennessee,US,10366,195,0
151,4/29/2020,NaN,South Korea,10765,247,9059
171,4/29/2020,NaN,United Arab Emirates,11929,98,2329
133,4/29/2020,NaN,Romania,11978,693,3569
132,4/29/2020,NaN,Qatar,12564,10,1243
130,4/29/2020,NaN,Poland,12640,624,3025
14,4/29/2020,NaN,Belarus,13181,84,2072
83,4/29/2020,NaN,Japan,13895,413,2368
312,4/29/2020,Washington,US,14070,801,0
199,4/29/2020,Colorado,US,14758,766,0
33,4/29/2020,NaN,Chile,14885,216,8057
311,4/29/2020,Virginia,US,14962,522,0
8,4/29/2020,NaN,Austria,15402,580,12779
124,4/29/2020,NaN,Pakistan,15525,343,3425
146,4/29/2020,NaN,Singapore,15641,14,1188
79,4/29/2020,NaN,Israel,15834,215,8233
276,4/29/2020,Ontario,Canada,16978,1153,0
233,4/29/2020,Indiana,US,17182,964,0
274,4/29/2020,Ohio,US,17303,937,0
107,4/29/2020,NaN,Mexico,17799,1732,11423
78,4/29/2020,NaN,Ireland,20253,1190,13386
157,4/29/2020,NaN,Sweden,20302,2462,1005
248,4/29/2020,Maryland,US,20849,1078,0
141,4/29/2020,NaN,Saudi Arabia,21402,157,2953
131,4/29/2020,NaN,Portugal,24505,973,1470
47,4/29/2020,NaN,Ecuador,24675,883,1557
213,4/29/2020,Georgia,US,25775,1101,0
282,4/29/2020,Quebec,Canada,26610,1762,0
200,4/29/2020,Connecticut,US,26767,2169,0
303,4/29/2020,Texas,US,27257,754,0
243,4/29/2020,Louisiana,US,27660,1845,0
158,4/29/2020,NaN,Switzerland,29407,1716,22600
74,4/29/2020,NaN,India,33062,1079,8437
208,4/29/2020,Florida,US,33193,1218,0
128,4/29/2020,NaN,Peru,33931,943,10037
116,4/29/2020,NaN,Netherlands,38802,4711,0
251,4/29/2020,Michigan,US,40399,3670,0
278,4/29/2020,Pennsylvania,US,46327,2373,0
15,4/29/2020,NaN,Belgium,47859,7501,11283
195,4/29/2020,California,US,48747,1946,0
232,4/29/2020,Illinois,US,50358,2215,0
249,4/29/2020,Massachusetts,US,60265,3405,0
229,4/29/2020,Hubei,Mainland China,68128,4512,63616
22,4/29/2020,NaN,Brazil,79685,5513,34132
76,4/29/2020,NaN,Iran,93657,5957,73791
134,4/29/2020,NaN,Russia,99399,972,10286
262,4/29/2020,New Jersey,US,116365,6771,0
167,4/29/2020,NaN,Turkey,117589,3081,44040
61,4/29/2020,NaN,Germany,161539,6467,120400
57,4/29/2020,NaN,France,165093,24087,48228
168,4/29/2020,NaN,UK,165221,26097,0
80,4/29/2020,NaN,Italy,203591,27682,71252
153,4/29/2020,NaN,Spain,236899,24275,132929
265,4/29/2020,New York,US,299691,23477,0

### Sort the entire data wrt recovered cases in descending order.

In [55]:
data.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [56]:
data.sort_values(by = "Recovered" , ascending = False)

,Date,State,Region,Confirmed,Deaths,Recovered
153,4/29/2020,NaN,Spain,236899,24275,132929
61,4/29/2020,NaN,Germany,161539,6467,120400
76,4/29/2020,NaN,Iran,93657,5957,73791
80,4/29/2020,NaN,Italy,203591,27682,71252
229,4/29/2020,Hubei,Mainland China,68128,4512,63616
57,4/29/2020,NaN,France,165093,24087,48228
167,4/29/2020,NaN,Turkey,117589,3081,44040
22,4/29/2020,NaN,Brazil,79685,5513,34132
158,4/29/2020,NaN,Switzerland,29407,1716,22600
78,4/29/2020,NaN,Ireland,20253,1190,13386
8,4/29/2020,NaN,Austria,15402,580,12779
107,4/29/2020,NaN,Mexico,17799,1732,11423
15,4/29/2020,NaN,Belgium,47859,7501,11283
134,4/29/2020,NaN,Russia,99399,972,10286
128,4/29/2020,NaN,Peru,33931,943,10037
151,4/29/2020,NaN,South Korea,10765,247,9059
74,4/29/2020,NaN,India,33062,1079,8437
79,4/29/2020,NaN,Israel,15834,215,8233
33,4/29/2020,NaN,Chile,14885,216,8057
42,4/29/2020,NaN,Denmark,9008,443,6366
101,4/29/2020,NaN,Malaysia,5945,100,4087
133,4/29/2020,NaN,Romania,11978,693,3569
124,4/29/2020,NaN,Pakistan,15525,343,3425
97,4/29/2020,NaN,Luxembourg,3769,89,3134
41,4/29/2020,NaN,Czech Republic,7579,227,3108
130,4/29/2020,NaN,Poland,12640,624,3025
141,4/29/2020,NaN,Saudi Arabia,21402,157,2953
56,4/29/2020,NaN,Finland,4906,206,2800
162,4/29/2020,NaN,Thailand,2947,54,2665
83,4/29/2020,NaN,Japan,13895,413,2368
171,4/29/2020,NaN,United Arab Emirates,11929,98,2329
264,4/29/2020,New South Wales,Australia,3016,40,2284
150,4/29/2020,NaN,South Africa,5350,103,2073
14,4/29/2020,NaN,Belarus,13181,84,2072
2,4/29/2020,NaN,Algeria,3848,444,1702
73,4/29/2020,NaN,Iceland,1797,10,1656
47,4/29/2020,NaN,Ecuador,24675,883,1557
220,4/29/2020,Guangdong,Mainland China,1588,8,1557
131,4/29/2020,NaN,Portugal,24505,973,1470
11,4/29/2020,NaN,Bahrain,2921,8,1455
34,4/29/2020,NaN,Colombia,6207,278,1411
75,4/29/2020,NaN,Indonesia,9771,784,1391
88,4/29/2020,NaN,Kuwait,3740,24,1389
77,4/29/2020,NaN,Iraq,2003,92,1346
48,4/29/2020,NaN,Egypt,5268,380,1335
309,4/29/2020,Victoria,Australia,1361,18,1291
38,4/29/2020,NaN,Croatia,2062,67,1288
9,4/29/2020,NaN,Azerbaijan,1766,23,1267
320,4/29/2020,Zhejiang,Mainland China,1268,1,1263
227,4/29/2020,Henan,Mainland China,1276,22,1254
132,4/29/2020,NaN,Qatar,12564,10,1243
117,4/29/2020,NaN,New Zealand,1476,19,1241
46,4/29/2020,NaN,Dominican Republic,6652,293,1228
6,4/29/2020,NaN,Argentina,4285,214,1192
146,4/29/2020,NaN,Singapore,15641,14,1188
108,4/29/2020,NaN,Moldova,3771,111,1114
170,4/29/2020,NaN,Ukraine,9866,250,1103
173,4/29/2020,NaN,Uzbekistan,2002,9,1096
129,4/29/2020,NaN,Philippines,8212,558,1023
230,4/29/2020,Hunan,Mainland China,1019,4,1015
157,4/29/2020,NaN,Sweden,20302,2462,1005
185,4/29/2020,Anhui,Mainland China,991,6,985
283,4/29/2020,Queensland,Australia,1033,6,943
238,4/29/2020,Jiangxi,Mainland China,937,1,936
30,4/29/2020,NaN,Cameroon,1832,61,934
112,4/29/2020,NaN,Morocco,4321,168,928
7,4/29/2020,NaN,Armenia,1932,30,900
143,4/29/2020,NaN,Serbia,6630,125,870
228,4/29/2020,Hong Kong,Hong Kong,1037,4,830
85,4/29/2020,NaN,Kazakhstan,3138,25,819
292,4/29/2020,Shandong,Mainland China,787,7,772
20,4/29/2020,NaN,Bosnia and Herzegovina,1677,65,710
237,4/29/2020,Jiangsu,Mainland China,653,0,648
43,4/29/2020,NaN,Diamond Princess,712,13,645
121,4/29/2020,NaN,North Macedonia,1442,73,627
39,4/29/2020,NaN,Cuba,1467,58,617
44,4/29/2020,NaN,Djibouti,1077,2,599
293,4/29/2020,Shanghai,Mainland China,647,7,597
226,4/29/2020,Heilongjiang,Mainland China,939,13,587
63,4/29/2020,NaN,Greece,2576,139,577
198,4/29/2020,Chongqing,Mainland China,579,6,573
96,4/29/2020,NaN,Lithuania,1375,45,563
295,4/29/2020,Sichuan,Mainland China,561,3,558
81,4/29/2020,NaN,Ivory Coast,1238,14,557
190,4/29/2020,Beijing,Mainland China,593,9,542
72,4/29/2020,NaN,Hungary,2727,300,536
125,4/29/2020,NaN,Panama,6378,178,527
314,4/29/2020,Western Australia,Australia,551,8,507
25,4/29/2020,NaN,Burkina Faso,641,43,498
147,4/29/2020,NaN,Slovakia,1391,22,484
1,4/29/2020,NaN,Albania,766,30,455
89,4/29/2020,NaN,Kyrgyzstan,729,8,437
119,4/29/2020,NaN,Niger,713,32,435
3,4/29/2020,NaN,Andorra,743,42,423
297,4/29/2020,South Australia,Australia,438,4,420
172,4/29/2020,NaN,Uruguay,630,15,412
197,4/29/2020,Channel Islands,UK,537,38,386
123,4/29/2020,NaN,Oman,2274,10,364
84,4/29/2020,NaN,Jordan,451,8,356
211,4/29/2020,Fujian,Mainland China,355,1,353
91,4/29/2020,NaN,Latvia,849,15,348
104,4/29/2020,NaN,Malta,463,4,339
37,4/29/2020,NaN,Costa Rica,713,6,323
225,4/29/2020,Hebei,Mainland China,328,6,318
142,4/29/2020,NaN,Senegal,882,9,315
66,4/29/2020,NaN,Guinea,1351,7,313
160,4/29/2020,NaN,Taiwan,429,6,311
120,4/29/2020,NaN,Nigeria,1728,51,307
106,4/29/2020,NaN,Mauritius,332,10,306
286,4/29/2020,Reunion,France,420,0,300
166,4/29/2020,NaN,Tunisia,980,40,294
236,4/29/2020,Isle of Man,UK,313,21,258
291,4/29/2020,Shaanxi,Mainland China,306,3,253
221,4/29/2020,Guangxi,Mainland China,254,2,252
0,4/29/2020,NaN,Afghanistan,1939,60,252
24,4/29/2020,NaN,Bulgaria,1447,64,243
52,4/29/2020,NaN,Estonia,1666,50,236
250,4/29/2020,Mayotte,France,460,4,235
148,4/29/2020,NaN,Slovenia,1418,89,230
175,4/29/2020,NaN,Vietnam,270,0,222
111,4/29/2020,NaN,Montenegro,322,7,203
62,4/29/2020,NaN,Ghana,1671,16,188
304,4/29/2020,Tianjin,Mainland China,190,3,183
319,4/29/2020,Yunnan,Mainland China,185,2,181
207,4/29/2020,Faroe Islands,Denmark,187,0,181
60,4/29/2020,NaN,Georgia,517,6,178
161,4/29/2020,NaN,Tanzania,480,16,167
294,4/29/2020,Shanxi,Mainland China,197,0,164
223,4/29/2020,Hainan,Mainland China,168,6,162
234,4/29/2020,Inner Mongolia,Mainland China,200,1,150
92,4/29/2020,NaN,Lebanon,721,24,150
12,4/29/2020,NaN,Bangladesh,7103,163,150
40,4/29/2020,NaN,Cyprus,843,15,148
222,4/29/2020,Guizhou,Mainland China,147,2,145
301,4/29/2020,Tasmania,Australia,219,12,144
242,4/29/2020,Liaoning,Mainland China,146,2,143
174,4/29/2020,NaN,Venezuela,331,10,142
212,4/29/2020,Gansu,Mainland China,139,2,137
154,4/29/2020,NaN,Sri Lanka,649,7,136
214,4/29/2020,Gibraltar,UK,141,0,131
103,4/29/2020,NaN,Mali,482,25,129
86,4/29/2020,NaN,Kenya,384,15,129
23,4/29/2020,NaN,Brunei,138,1,124
29,4/29/2020,NaN,Cambodia,122,0,119
19,4/29/2020,NaN,Bolivia,1110,59,117
49,4/29/2020,NaN,El Salvador,377,9,106
127,4/29/2020,NaN,Paraguay,239,9,102
189,4/29/2020,Australian Capital Territory,Australia,106,3,101
239,4/29/2020,Jilin,Mainland China,111,1,99
135,4/29/2020,NaN,Rwanda,225,0,98
87,4/29/2020,NaN,Kosovo,510,12,93
209,4/29/2020,French Guiana,France,125,1,93
99,4/29/2020,NaN,Madagascar,128,0,90
247,4/29/2020,Martinique,France,175,14,83
218,4/29/2020,Guadeloupe,France,149,12,82
267,4/29/2020,Ningxia,Mainland China,75,0,75
71,4/29/2020,NaN,Honduras,738,66,73
317,4/29/2020,Xinjiang,Mainland China,76,3,73
188,4/29/2020,Aruba,Netherlands,100,2,73
176,4/29/2020,NaN,West Bank and Gaza,344,2,71
165,4/29/2020,NaN,Trinidad and Tobago,116,8,71
139,4/29/2020,NaN,San Marino,563,41,69
58,4/29/2020,NaN,Gabon,276,3,67
164,4/29/2020,NaN,Togo,109,7,64
65,4/29/2020,NaN,Guatemala,557,16,62
36,4/29/2020,NaN,Congo (Kinshasa),491,30,59
54,4/29/2020,NaN,Ethiopia,130,3,58
109,4/29/2020,NaN,Monaco,95,4,58
95,4/29/2020,NaN,Liechtenstein,82,1,55
179,4/29/2020,NaN,Zambia,97,3,54
169,4/29/2020,NaN,Uganda,81,0,52
210,4/29/2020,French Polynesia,France,58,0,50
191,4/29/2020,Bermuda,UK,111,6,48
93,4/29/2020,NaN,Liberia,141,16,45
13,4/29/2020,NaN,Barbados,80,7,39
244,4/29/2020,Macau,Macau,45,0,34
296,4/29/2020,Sint Maarten,Netherlands,75,13,33
17,4/29/2020,NaN,Benin,64,1,33
122,4/29/2020,NaN,Norway,7710,207,32
155,4/29/2020,NaN,Sudan,375,28,32
82,4/29/2020,NaN,Jamaica,396,7,29
26,4/29/2020,NaN,Burma,150,6,27
271,4/29/2020,Northern Territory,Australia,28,0,25
300,4/29/2020,St Martin,France,38,3,24
10,4/29/2020,NaN,Bahamas,80,11,23
159,4/29/2020,NaN,Syria,43,3,21
149,4/29/2020,NaN,Somalia,582,28,20
51,4/29/2020,NaN,Eritrea,39,0,19
32,4/29/2020,NaN,Chad,52,2,19
67,4/29/2020,NaN,Guinea-Bissau,205,1,19
35,4/29/2020,NaN,Congo (Brazzaville),207,8,19
281,4/29/2020,Qinghai,Mainland China,18,0,18
94,4/29/2020,NaN,Libya,61,2,18
68,4/29/2020,NaN,Guyana,78,8,18
102,4/29/2020,NaN,Maldives,278,1,17
260,4/29/2020,New Caledonia,France,18,0,17
115,4/29/2020,NaN,Nepal,57,0,16
137,4/29/2020,NaN,Saint Lucia,17,0,15
201,4/29/2020,Curacao,Netherlands,16,1,13
64,4/29/2020,NaN,Grenada,20,0,13
45,4/29/2020,NaN,Dominica,16,0,13
55,4/29/2020,NaN,Fiji,18,0,12
145,4/29/2020,NaN,Sierra Leone,104,4,12
113,4/29/2020,NaN,Mozambique,76,0,12
217,4/29/2020,Greenland,Denmark,11,0,11
5,4/29/2020,NaN,Antigua and Barbuda,24,3,11
206,4/29/2020,Falkland Islands (Malvinas),UK,13,0,11
110,4/29/2020,NaN,Mongolia,38,0,10
31,4/29/2020,NaN,Central African Republic,50,0,10
196,4/29/2020,Cayman Islands,UK,73,1,10
53,4/29/2020,NaN,Eswatini,91,1,10
50,4/29/2020,NaN,Equatorial Guinea,315,1,9
16,4/29/2020,NaN,Belize,18,2,9
69,4/29/2020,NaN,Haiti,76,6,8
59,4/29/2020,NaN,Gambia,10,1,8
156,4/29/2020,NaN,Suriname,10,1,8
114,4/29/2020,NaN,Namibia,16,0,8
138,4/29/2020,NaN,Saint Vincent and the Grenadines,16,0,8
4,4/29/2020,NaN,Angola,27,2,7
118,4/29/2020,NaN,Nicaragua,13,3,7
100,4/29/2020,NaN,Malawi,36,3,7
90,4/29/2020,NaN,Laos,19,0,7
163,4/29/2020,NaN,Timor-Leste,24,0,6
144,4/29/2020,NaN,Seychelles,11,0,6
180,4/29/2020,NaN,Zimbabwe,32,4,5
21,4/29/2020,NaN,Botswana,23,1,5
306,4/29/2020,Turks and Caicos Islands,UK,12,1,5
136,4/29/2020,NaN,Saint Kitts and Nevis,15,0,4
27,4/29/2020,NaN,Burundi,11,1,4
28,4/29/2020,NaN,Cabo Verde,114,1,2
256,4/29/2020,Montserrat,UK,11,1,2
70,4/29/2020,NaN,Holy See,10,0,2
186,4/29/2020,Arizona,US,7209,308,0
181,4/29/2020,Alabama,US,6912,256,0
182,4/29/2020,Alaska,US,355,9,0
183,4/29/2020,Alberta,Canada,5165,87,0
277,4/29/2020,Oregon,US,2446,101,0
280,4/29/2020,Puerto Rico,US,1433,86,0
193,4/29/2020,British Columbia,Canada,2087,109,0
278,4/29/2020,Pennsylvania,US,46327,2373,0
287,4/29/2020,Rhode Island,US,8247,251,0
187,4/29/2020,Arkansas,US,3193,57,0
279,4/29/2020,Prince Edward Island,Canada,27,0,0
282,4/29/2020,Quebec,Canada,26610,1762,0
290,4/29/2020,Saskatchewan,Canada,383,6,0
299,4/29/2020,South Dakota,US,2373,13,0
168,4/29/2020,NaN,UK,165221,26097,0
298,4/29/2020,South Carolina,US,5882,231,0
275,4/29/2020,Oklahoma,US,3473,214,0
302,4/29/2020,Tennessee,US,10366,195,0
303,4/29/2020,Texas,US,27257,754,0
152,4/29/2020,NaN,South Sudan,34,0,0
307,4/29/2020,Utah,US,4497,45,0
308,4/29/2020,Vermont,US,862,47,0
310,4/29/2020,Virgin Islands,US,57,4,0
311,4/29/2020,Virginia,US,14962,522,0
312,4/29/2020,Washington,US,14070,801,0
313,4/29/2020,West Virginia,US,1110,38,0
315,4/29/2020,Wisconsin,US,6520,308,0
316,4/29/2020,Wyoming,US,545,7,0
318,4/29/2020,Yukon,Canada,11,0,0
276,4/29/2020,Ontario,Canada,16978,1153,0
231,4/29/2020,Idaho,US,1952,60,0
232,4/29/2020,Illinois,US,50358,2215,0
251,4/29/2020,Michigan,US,40399,3670,0
249,4/29/2020,Massachusetts,US,60265,3405,0
248,4/29/2020,Maryland,US,20849,1078,0
205,4/29/2020,District of Columbia,US,4106,205,0
246,4/29/2020,Manitoba,Canada,275,6,0
245,4/29/2020,Maine,US,1056,52,0
208,4/29/2020,Florida,US,33193,1218,0
243,4/29/2020,Louisiana,US,27660,1845,0
213,4/29/2020,Georgia,US,25775,1101,0
241,4/29/2020,Kentucky,US,4537,234,0
240,4/29/2020,Kansas,US,3839,134,0
215,4/29/2020,Grand Princess,Canada,13,0,0
216,4/29/2020,Grand Princess,US,103,3,0
219,4/29/2020,Guam,US,141,5,0
116,4/29/2020,NaN,Netherlands,38802,4711,0
235,4/29/2020,Iowa,US,6843,148,0
224,4/29/2020,Hawaii,US,613,16,0
233,4/29/2020,Indiana,US,17182,964,0
204,4/29/2020,Diamond Princess cruise ship,US,49,0,0
252,4/29/2020,Minnesota,US,4644,319,0
273,4/29/2020,Nova Scotia,Canada,935,28,0
253,4/29/2020,Mississippi,US,6569,250,0
195,4/29/2020,California,US,48747,1946,0
270,4/29/2020,Northern Mariana Islands,US,14,2,0
269,4/29/2020,North Dakota,US,1033,19,0
268,4/29/2020,North Carolina,US,10180,382,0
199,4/29/2020,Colorado,US,14758,766,0
266,4/29/2020,Newfoundland and Labrador,Canada,258,3,0
265,4/29/2020,New York,US,299691,23477,0
200,4/29/2020,Connecticut,US,26767,2169,0
263,4/29/2020,New Mexico,US,3213,112,0
262,4/29/2020,New Jersey,US,116365,6771,0
261,4/29/2020,New Hampshire,US,2058,60,0
202,4/29/2020,Delaware,US,4655,144,0
259,4/29/2020,New Brunswick,Canada,118,0,0
258,4/29/2020,Nevada,US,4934,230,0
257,4/29/2020,Nebraska,US,3851,56,0
255,4/29/2020,Montana,US,451,16,0
254,4/29/2020,Missouri,US,7660,338,0
274,4/29/2020,Ohio,US,17303,937,0

## Thank You

# Sumit Bhatia